# Generated by Django 4.0 on 2021-12-18 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Ip',
            fields=[
                ('ip', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('payload', models.JSONField()),
                ('modified', models.DateTimeField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.country')),
            ],
        ),
    ]
